services:
  esphome:
    container_name: esphome
    image: ghcr.io/esphome/esphome:stable
    hostname: esphome
    command: dashboard /config
    restart: unless-stopped
    ports:
      - 6052:6052
    environment:
      - TZ
      - UMASK
      - ESPHOME_DASHBOARD_USE_PING=true
    volumes:
      - ./esphome:/config
      - /etc/localtime:/etc/localtime:ro
    privileged: true
    labels:
      - haus.dondon.cname=esphome
      - haus.dondon.port=6052

  double-take:
    container_name: double-take
    image: ghcr.io/skrashevich/double-take:main
    restart: unless-stopped
    user: 1000:1000
    ports:
      - 3000:3000
    volumes:
      - ./double-take/storage:/.storage
      - ./double-take/config.yml:/.storage/config.yml

  ai-server:
    container_name: ai-server
    image: codeproject/ai-server:cuda12_2
    runtime: nvidia
    restart: unless-stopped
    ports:
      - 32168:32168
    environment:
      - TZ
      - NVIDIA_VISIBLE_DEVICES
      - NVIDIA_DRIVER_CAPABILITIES
    volumes:
      - ./codeproject.ai/etc:/etc/codeproject/ai
      - ./codeproject.ai/modules:/app/modules

  jellyfin:
    container_name: jellyfin
    image: lscr.io/linuxserver/jellyfin:latest
    runtime: nvidia
    restart: unless-stopped
    environment:
      - PUID
      - PGID
      - TZ
      - NVIDIA_VISIBLE_DEVICES
      - NVIDIA_DRIVER_CAPABILITIES
    volumes:
      - ./jellyfin:/config
      # - /mnt/homelab_storage/tv:/data/tvshows
      # - /mnt/homelab_storage/movies:/data/movies

networks:
  esphome-net:
  # local-net:
  #   name: 00_local-net
  #   driver: macvlan
  #   driver_opts:
  #     parent: wlp3s0
  #   ipam:
  #     config:
  #       - subnet: 192.168.84.0/22
  #         gateway: 192.168.86.1
  #         ip_range: 192.168.85.0/26
  #         aux_addresses:
  #           host: 192.168.85.0
