esphome:
  platformio_options:
    build_flags: -DBOARD_HAS_PSRAM
    board_build.arduino.memory_type: qio_opi
    board_build.f_flash: 80000000L
    board_build.flash_mode: qio

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

psram:
  mode: octal
  speed: 80000000.0

esp32_camera:
  id: espcam
  name: My Camera
  external_clock:
    pin: 10
    frequency: 20MHz
  i2c_pins:
    sda: 40
    scl: 39
  data_pins: [15, 17, 18, 16, 14, 12, 11, 48]
  vsync_pin: 38
  href_pin: 47
  pixel_clock_pin: 13
  resolution: 800x600
  max_framerate: 30.0fps
  wb_mode: CLOUDY
  agc_gain_ceiling: 16X

esp32_camera_web_server:
  - port: 8080
    mode: stream
  - port: 8081
    mode: snapshot

# Configuration for I2S audio
i2s_audio:
  i2s_lrclk_pin: 46 # Note: labeled as "useless"
  i2s_bclk_pin: 42

# Configuration for the microphone using I2S audio
microphone:
  - platform: i2s_audio
    id: echo_microphone
    i2s_din_pin: 41
    adc_type: external
    pdm: true
