<<: !include './device-ip-map.yaml'

defaults:
  # Left switch
  switch_1_name: "1"
  # Right switch
  switch_2_name: "1"

esphome:
  friendly_name: $friendly_name
  name: $name

esp32:
  board: esp32dev

logger:

# wifi:
#   ssid: !secret wifi_ssid
#   password: !secret wifi_password

#   manual_ip:
#     static_ip: ${ip_${name}}
#     gateway: 192.168.0.1
#     subnet: 255.255.255.0

# api:

# ota:
#   - platform: esphome

# uart:
#   tx_pin: 25
#   rx_pin: 26
#   baud_rate: 4800
#   parity: NONE
#   stop_bits: 2

# button:
#   - platform: restart
#     name: "Restart"
#     id: button_restart

# light:
#   - platform: status_led
#     name: "LED"
#     id: led_status
#     pin:
#       number: 13
#       inverted: True
#     internal: True

# switch:
#   - platform: gpio
#     name: "$switch_1_name Relay"
#     pin: 27
#     id: relay_1

#   - platform: gpio
#     name: "$switch_2_name Relay"
#     pin: 14
#     id: relay_2

# binary_sensor:
#   - platform: gpio
#     name: "$switch_1_name Push Button (inverted)"
#     id: sensor_button
#     pin:
#       number: 0
#       mode:
#         input: True
#         pullup: True
#       inverted: True
#     disabled_by_default: True
#     icon: 'mdi:radiobox-blank'
#     filters:
#       - delayed_on: 50ms
#     on_press:
#       - switch.toggle: relay_1

#   - platform: gpio
#     name: "$switch_1_name Switch (inverted)"
#     pin:
#       number: 32
#       mode:
#         input: True
#         pullup: True
#       inverted: True
#     filters:
#       - delayed_on_off: 50ms
#     on_press:
#       - switch.turn_on: relay_1
#     on_release:
#       - switch.turn_off: relay_1

#   - platform: gpio
#     name: "$switch_2_name Switch (inverted)"
#     pin:
#       number: 33
#       mode:
#         input: True
#         pullup: True
#       inverted: True
#     filters:
#       - delayed_on_off: 50ms
#     on_press:
#       - switch.turn_on: relay_2
#     on_release:
#       - switch.turn_off: relay_2

# sensor:
#   - platform: bl0939
#     update_interval: 30s
#     voltage:
#       name: 'Voltage'
#     current_1:
#       name: '$switch_1_name Current'
#       disabled_by_default: True
#     current_2:
#       name: '$switch_2_name Current'
#       disabled_by_default: True
#     active_power_1:
#       name: '$switch_1_name Power'
#     active_power_2:
#       name: '$switch_2_name Power'
#     energy_1:
#       name: '$switch_1_name Energy'
#     energy_2:
#       name: '$switch_2_name Energy'
#     energy_total:
#       name: 'Energy Total'
#   - platform: wifi_signal
#     name: "$friendly_name RSSI"
#     id: sensor_rssi
#     update_interval: 60s
#     entity_category: "diagnostic"

#   - platform: uptime
#     name: "$friendly_name Uptime"
#     id: sensor_uptime
#     update_interval: 60s
#     entity_category: "diagnostic"
