substitutions:
  friendly_name: Fancy Theoretical Thermostat v1.5.0
  name: theoretical_thermostat

packages:
  device-base: !include
    file: packages/device-base.yaml

esphome:
  platformio_options:
    build_unflags: -Werror=all
    board_build.flash_mode: dio

esp32:
  board: esp32-s3-devkitc-1
  flash_size: 16MB
  framework:
    type: esp-idf
    sdkconfig_options:
      COMPILER_OPTIMIZATION_SIZE: y
      type: esp-idf


spi:
  id: quad_spi
  type: quad
  clk_pin: 15
  data_pins: [14, 10, 16, 12]

i2c:
  sda: 6
  scl: 7

psram:psram:
  mode: octal
  speed: 80MHz

  mode: octal
  speed: 80MHz

touchscreen:
  - platform: cst226
    id: my_touchscreen
    interrupt_pin: 8
    reset_pin: 17


font:
  - id: primary_stat_font
    file:
      type: gfonts
      family: Roboto
      weight: Bold
    size: 108
    glyphs: '!"%()+=,-_.:°³/0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz'
    bpp: 4
  - id: secondary_stat_font
    file: 'gfonts://Roboto+Mono'
    size: 48
    glyphs: '!"%()+=,-_.:°³/0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz'
    bpp: 4

display:
  - platform: qspi_amoled
    model: RM690B0
    data_rate: 80MHz
    spi_mode: mode0
    dimensions:
      width: 450
      height: 600
      offset_width: 16
    color_order: rgb
    invert_colors: false
    brightness: 255
    cs_pin: 11
    reset_pin: 13
    enable_pin: 9
    update_interval: 5s
    auto_clear_enabled: false
    lambda: |-
      it.printf(0, 0, id(primary_stat_font), "%.1f°C", 16.4);
