substitutions:
  friendly_name: Front Hall Wall Switches
  name: front_hall_switches

<<: !include
  file: 'packages/sonoff-dual-r3.yaml'
  vars:
    switch_1_name: Front Hall Light
    switch_2_name: Front Porch Light
